# Generated by Django 3.2.9 on 2021-11-13 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Automaker name')),
                ('foundation_year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1821), django.core.validators.MaxValueValidator(2021)], verbose_name="Year of company's foundation")),
                ('location', models.CharField(max_length=32, verbose_name='Location of head office')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Information about company')),
            ],
            options={
                'verbose_name': 'Автопроизводитель',
                'verbose_name_plural': 'Автопроизводители',
                'db_table': 'automakers',
                'ordering': ['name'],
            },
        ),
    ]
