# Generated by Django 3.2.9 on 2021-11-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automakers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64, verbose_name='Car model')),
                ('type_of_drive', models.CharField(max_length=3, verbose_name='type of wheel drive (4WD, BWD, FWD)')),
                ('price', models.IntegerField(verbose_name='average price of car ($)')),
                ('year', models.CharField(max_length=10, verbose_name='Period of car manufacturing')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='Information about car')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Topic creator')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automakers.automaker', verbose_name='Automaker name')),
            ],
        ),
    ]
